site_name: THE AEC PROGRAMMER
site_description: Coding for the AEC Industry
copyright: |
  Copyright &copy; 2021-2023 Eduardo Di Loreto
strict: false

theme:
  name: "material"
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: "Turn off the lights"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: "Turn on the lights"

nav:
    - "About Me": 'index.md'
    - Revit:
        - "Select Elements": revit/select_elements.md
        - "Read and Write Parameters": revit/parameters.md
    - Rhino: coming_soon_rhino.md
    - Tekla: coming_soon_tekla.md
    - IFC: coming_soon_ifc.md

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"

plugins:
  - mkdocstrings
  - search

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-XXXXXXXXXX